# These are supported funding model platforms


ko_fi: talos91
custom: 
  - 'https://www.paypal.com/donate/?hosted_button_id=P3NVBYRQ4Z45L' #Ilyaki -> ttps://github.com/Ilyaki
  - 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WUXKHLAD3A3LE&source=url' #Zerofox5866 -> https://github.com/ZeroFox5866
  - 'https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=HH97DSPF3MPKQ&source=url' #Mikou27 -> https://github.com/Mikou27
